import {
  Layout,
  ShoppingCart,
  CreditCard,
  Package,
  Truck,
  Tags,
  Users,
  Mail,
  Globe,
  CalendarClock,
  BarChart3,
  Share2,
  Star,
  Search,
  FileSpreadsheet,
  Plug,
  MessageSquare,
  FileText,
  Lock,
  UserCheck,
  Bell,
  LayoutDashboard,
  Upload,
  Filter,
  Calendar,
  UserCircle,
  Wifi,
  Bot,
  MessageCircle,
  Languages,
  Workflow,
  FileDown,
  ClipboardList,
  BarChart,
  MessagesSquare,
  MousePointerClick,
  CreditCard as Payment,
} from 'lucide-react';
import { Feature } from '../types';

export const wordpressFeatures: Feature[] = [
  {
    id: 'blog',
    name: 'Blog Integration',
    description: 'Share your expertise with a fully-featured blog section',
    icon: Layout,
  },
  {
    id: 'contact-forms',
    name: 'Advanced Contact Forms',
    description: 'Custom forms with conditional logic and integrations',
    icon: Mail,
  },
  {
    id: 'seo',
    name: 'SEO Optimization',
    description: 'Optimize your site for better search engine visibility',
    icon: Search,
  },
  {
    id: 'analytics',
    name: 'Advanced Analytics',
    description: 'Track and analyze your website performance',
    icon: BarChart3,
  },
  {
    id: 'social-media',
    name: 'Social Media Integration',
    description: 'Connect your site with your social platforms',
    icon: Share2,
  },
  {
    id: 'custom-forms',
    name: 'Custom Forms and Surveys',
    description: 'Collect feedback or data from visitors',
    icon: FileText,
  },
  {
    id: 'multi-language',
    name: 'Multi-Language Support',
    description: 'Reach a wider audience by offering multiple languages',
    icon: Globe,
  },
  {
    id: 'faq',
    name: 'FAQ Section',
    description: 'Answer common questions directly on your site',
    icon: MessageSquare,
  },
  {
    id: 'membership',
    name: 'Membership/Restricted Content Area',
    description: 'Offer exclusive content to registered users',
    icon: Lock,
    customQuote: true,
  },
];

export const webAppFeatures: Feature[] = [
  {
    id: 'user-auth',
    name: 'User Registration and Authentication',
    description: 'Allow users to create accounts and log in securely',
    icon: UserCheck,
  },
  {
    id: 'role-based-access',
    name: 'Role-Based Access Control',
    description: 'Tailor access to different user types',
    icon: Lock,
  },
  {
    id: 'real-time-notifications',
    name: 'Real-Time Notifications',
    description: 'Keep users informed instantly',
    icon: Bell,
  },
  {
    id: 'dashboard-analytics',
    name: 'Dashboard and Analytics',
    description: 'Provide users with a clear view of key data',
    icon: LayoutDashboard,
  },
  {
    id: 'api-integration',
    name: 'API Integration',
    description: 'Connect your app to other tools and services',
    icon: Plug,
  },
  {
    id: 'file-management',
    name: 'File Upload and Management',
    description: 'Make it easy for users to share and organize files',
    icon: Upload,
  },
  {
    id: 'advanced-search',
    name: 'Advanced Search and Filters',
    description: 'Help users find exactly what they need',
    icon: Filter,
    customQuote: true,
  },
  {
    id: 'payment-processing',
    name: 'Payment Processing',
    description: 'Securely handle payments within the app',
    icon: CreditCard,
  },
  {
    id: 'collaboration',
    name: 'Collaboration Tools',
    description: 'Enable teamwork within the app',
    icon: Users,
  },
  {
    id: 'calendar',
    name: 'Scheduling and Calendar Integration',
    description: 'Keep track of events and appointments',
    icon: Calendar,
  },
  {
    id: 'offline-mode',
    name: 'Offline Mode',
    description: 'Allow access to key features without internet',
    icon: Wifi,
    customQuote: true,
  },
  {
    id: 'user-profiles',
    name: 'Customizable User Profiles',
    description: 'Let users personalize their experience',
    icon: UserCircle,
  },
  {
    id: 'iot-integration',
    name: 'Integration with IoT Devices',
    description: 'Connect your app to Internet of Things (IoT) devices',
    icon: Plug,
    customQuote: true,
  },
  {
    id: 'ai-insights',
    name: 'AI-Powered Insights',
    description: 'Leverage artificial intelligence to improve user experience',
    icon: Bot,
    customQuote: true,
  },
  {
    id: 'feedback-support',
    name: 'Feedback and Support System',
    description: 'Make it easy for users to share feedback or get help',
    icon: MessageCircle,
  },
  {
    id: 'multi-language',
    name: 'Multi-Language Support',
    description: 'Serve a global audience effortlessly',
    icon: Languages,
  },
  {
    id: 'workflow-automation',
    name: 'Workflow Automation',
    description: 'Streamline repetitive tasks for efficiency',
    icon: Workflow,
    customQuote: true,
  },
  {
    id: 'data-export',
    name: 'Data Export and Import',
    description: 'Let users manage their data flexibly',
    icon: FileDown,
    customQuote: true,
  },
  {
    id: 'activity-logs',
    name: 'Activity Logs',
    description: 'Track and audit user actions within the app',
    icon: ClipboardList,
  },
  {
    id: 'custom-reporting',
    name: 'Custom Reporting Tools',
    description: 'Generate tailored reports with ease',
    icon: BarChart,
    customQuote: true,
  },
  {
    id: 'live-chat',
    name: 'Live Chat Support',
    description: 'Provide real-time assistance to users',
    icon: MessagesSquare,
  },
  {
    id: 'drag-drop',
    name: 'Drag-and-Drop Functionality',
    description: 'Make interactions intuitive and easy',
    icon: MousePointerClick,
    customQuote: true,
  },
  {
    id: 'membership-payments',
    name: 'Membership / Recurring Payments',
    description: 'Offer seamless subscription services for your users',
    icon: Payment,
    customQuote: true,
  },
];

export const existingSiteFeatures: Feature[] = [
  {
    id: 'blog',
    name: 'Blog Integration',
    description: 'Share updates, articles, or news effortlessly',
    icon: Layout,
  },
  {
    id: 'contact-forms',
    name: 'Advanced Contact Forms',
    description: 'Get more detailed information from visitors',
    icon: Mail,
  },
  {
    id: 'analytics',
    name: 'Advanced Analytics',
    description: 'Track user behavior and make data-driven decisions',
    icon: BarChart3,
  },
  {
    id: 'social-media',
    name: 'Social Media Integration',
    description: 'Connect your website to your social channels',
    icon: Share2,
  },
  {
    id: 'multi-language',
    name: 'Multi-Language Support',
    description: 'Reach a global audience with language options',
    icon: Globe,
  },
  {
    id: 'faq',
    name: 'FAQ Section',
    description: 'Answer common questions directly on your site',
    icon: MessageSquare,
  },
  {
    id: 'membership',
    name: 'Membership / Restricted Area',
    description: 'Offer exclusive content or services to members',
    icon: Lock,
    customQuote: true,
  },
  {
    id: 'redesign',
    name: 'Site Redesign',
    description: 'Give your website a fresh, modern look',
    icon: Layout,
  },
  {
    id: 'speed',
    name: 'Speed Optimization',
    description: 'Make your website load faster for a better user experience',
    icon: Plug,
  },
  {
    id: 'seo',
    name: 'SEO Audit and Improvement',
    description: 'Boost your site\'s visibility on search engines',
    icon: Search,
    customQuote: true,
  },
  {
    id: 'mobile',
    name: 'Mobile Responsiveness Update',
    description: 'Ensure your site looks great on all devices',
    icon: Layout,
  },
  {
    id: 'security',
    name: 'Security Enhancements',
    description: 'Protect your site from hackers and malware',
    icon: Lock,
    customQuote: true,
  },
  {
    id: 'content',
    name: 'Content Updates',
    description: 'Keep your site fresh and relevant',
    icon: FileText,
  },
  {
    id: 'plugins',
    name: 'Plugin Updates and Optimization',
    description: 'Ensure your website\'s tools are up-to-date',
    icon: Plug,
  },
  {
    id: 'bug-fixes',
    name: 'Bug Fixes and Troubleshooting',
    description: 'Resolve technical issues quickly',
    icon: Workflow,
    customQuote: true,
  },
  {
    id: 'third-party',
    name: 'Integration with Third-Party Tools',
    description: 'Connect your site to the tools you use every day',
    icon: Plug,
    customQuote: true,
  },
  {
    id: 'hosting',
    name: 'Hosting Migration',
    description: 'Move your site to a better hosting provider',
    icon: Globe,
    customQuote: true,
  },
  {
    id: 'accessibility',
    name: 'Accessibility Compliance',
    description: 'Make your website usable for everyone',
    icon: Users,
  },
  {
    id: 'ecommerce',
    name: 'E-Commerce Integration',
    description: 'Expand your existing site with online sales capabilities',
    icon: ShoppingCart,
    customQuote: true,
  },
  {
    id: 'forms',
    name: 'Advanced Forms and Surveys',
    description: 'Collect better insights from your audience',
    icon: FileText,
  },
  {
    id: 'backup',
    name: 'Backup and Restore Services',
    description: 'Protect your website from data loss',
    icon: FileDown,
    customQuote: true,
  },
  {
    id: 'custom-features',
    name: 'Custom Features or Add-Ons',
    description: 'Enhance your site with tailored functionality',
    icon: Plug,
    customQuote: true,
  },
  {
    id: 'cms-training',
    name: 'Content Management System (CMS) Training',
    description: 'Learn to manage your website with confidence',
    icon: Users,
    customQuote: true,
  },
  {
    id: 'maintenance',
    name: 'Performance Monitoring and Maintenance',
    description: 'Keep your site running smoothly over time',
    icon: BarChart3,
    customQuote: true,
  },
];

export const ecommerceFeatures: Feature[] = [
  {
    id: 'fulfillment',
    name: '3rd Party Fulfillment Integration',
    description: 'Send orders seamlessly to your fulfillment partner',
    icon: Package,
    customQuote: true,
  },
  {
    id: 'customer-login',
    name: 'Customer Login',
    description: 'Secure accounts for your customers',
    icon: Users,
  },
  {
    id: 'inventory',
    name: 'Inventory Management System',
    description: 'Keep track of stock levels in real time',
    icon: Package,
  },
  {
    id: 'shipping',
    name: 'Custom Shipping Options',
    description: 'Offer flexible shipping choices to your customers',
    icon: Truck,
  },
  {
    id: 'pricing',
    name: 'Dynamic Pricing and Discounts',
    description: 'Set special pricing rules and discounts automatically',
    icon: Tags,
  },
  {
    id: 'customization',
    name: 'Product Customization Options',
    description: 'Let customers personalize products',
    icon: Layout,
  },
  {
    id: 'notifications',
    name: 'Email and SMS Notifications',
    description: 'Keep customers updated at every step',
    icon: Mail,
  },
  {
    id: 'multi-language',
    name: 'Multi-Language and Currency Support',
    description: 'Expand your business globally',
    icon: Globe,
  },
  {
    id: 'subscription',
    name: 'Subscription Management',
    description: 'Offer recurring billing for subscription-based services',
    icon: CalendarClock,
    customQuote: true,
  },
  {
    id: 'analytics-dashboard',
    name: 'Advanced Analytics Dashboard',
    description: 'Track sales and customer behavior with ease',
    icon: BarChart3,
  },
  {
    id: 'social-media',
    name: 'Social Media Integration',
    description: 'Connect your store to your social platforms',
    icon: Share2,
  },
  {
    id: 'reviews',
    name: 'Product Reviews and Ratings',
    description: 'Build trust with customer feedback',
    icon: Star,
  },
  {
    id: 'search-filter',
    name: 'Search and Filter Functionality',
    description: 'Help customers find what they need faster',
    icon: Search,
    customQuote: true,
  },
  {
    id: 'reporting',
    name: 'Custom Reporting Tools',
    description: 'Generate detailed reports on demand',
    icon: FileSpreadsheet,
  },
  {
    id: 'api-integration',
    name: 'API Integration',
    description: 'Seamlessly connect with your existing tools',
    icon: Plug,
    customQuote: true,
  },
];